### ISSUE TITLE
strict-message-values has false positives for invalid rules

### ISSUE THREAD

**Issue by kumarharsh** [Mayank1791989/eslint-plugin-playlyfe#174]
For the given invalid ICU message:

```
<FormattedMessage
  id="msg"
  defaultMessage="Hello {wh{ich}"
  values={{ which: 'world' }}
/>
```

The error should point out that the message is invalid, but instead we get an `Unknown message arg 'which' value provided` message.

**Comment by Mayank1791989** [comment]
fixed in 9e8da3742e417d947f8d27d1dcda53cfaab6a3c2
